# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a89c95ad45f43adf1aec0ab46cb0d2bea852cd948e6e1731b3d175aa54ab71ae171b8e75c183816f3105e1c4987488ada777e54373dd8400f91a9ee5a14aa69d

test:
  secret_key_base: 019fba687f40b7e155f41c89c122b01b8e584dfb48c6b9ae77cc49974779133ad2dd65224dddeb33268065ce64951e466be759b68734cfdd0d6d38518478f01f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
